### PR TITLE
Support docker registry auth

### PR DESCRIPTION
**Pull request by apexskier**
This adds a new parameter to support docker registry authentication. This allows us to avoid rate limiting issues in our CI environment that we've been hitting frequently due to unauthenticated registry calls.

The parameter is a JSON object of the same form of the standard docker config json file, which means you can directly pass the config file or pass a manually created object. There's an empty default, so this is backwards compatible.

I've also added the `--progress plain` flag to the build, to make the ops output friendlier in CI environments.

### CODE REVIEW

**Comment by apexskier** [comment]
Ironic, the CI failure here is `You have reached your pull rate limit`

**Comment by apexskier** [comment]
This should be released as v1.1.0 - it's a new feature that's not a breaking change.

**Comment by chrisdostert** [comment]
The README.md actually is autogenerated from the op.yml when you run `opctl run build`. There's some docs on authoring. here; for editing only step 3+ really apply https://github.com/opspec-pkgs/project/blob/master/how-tos.md#step-3

**Comment by chrisdostert** [comment]
you can regenerate the latest ops by updating this reference to the latest bootstrap op which is 3.0.0 https://github.com/opspec-pkgs/docker.build.localimage/blob/6ae0a611740ff006e8ab88c2758690ccfb54578a/.opspec/build/op.yml#L17

**Comment by apexskier** [comment]
Updated to 3.0.0 in #7

**Comment by chrisdostert** [comment]
If you bump the version in the `op.yml` to what you will be releasing and run `opctl run build` the version references will be correct in the generated README.md

**Review by chrisdostert — APPROVED** [review]

**Pull request merged**
